// implementations/vue/src/App.vue
<script setup>
import { ref, computed } from 'vue';

// Generate initial todos
const generateInitialTodos = (count) => {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    text: `Todo item ${i + 1}`,
    completed: i % 3 === 0, // Every 3rd item is completed
  }));
};

const todos = ref(generateInitialTodos(100));
const inputValue = ref('');
const filter = ref('all'); // all, active, completed

// Add new todo
const addTodo = () => {
  if (inputValue.value.trim() === '') return;
  
  const newTodo = {
    id: Date.now(),
    text: inputValue.value,
    completed: false,
  };
  
  todos.value.unshift(newTodo);
  inputValue.value = '';
};

// Toggle todo completion
const toggleTodo = (id) => {
  const todo = todos.value.find(t => t.id === id);
  if (todo) {
    todo.completed = !todo.completed;
  }
};

// Delete todo
const deleteTodo = (id) => {
  todos.value = todos.value.filter(todo => todo.id !== id);
};

// Filter todos
const filteredTodos = computed(() => {
  switch (filter.value) {
    case 'active':
      return todos.value.filter(todo => !todo.completed);
    case 'completed':
      return todos.value.filter(todo => todo.completed);
    default:
      return todos.value;
  }
});

// Count remaining todos
const remainingCount = computed(() => 
  todos.value.filter(todo => !todo.completed).length
);

// Handle Enter key
const handleKeyPress = (e) => {
  if (e.key === 'Enter') {
    addTodo();
  }
};
</script>

<template>
  <div class="todo-app">
    <div class="todo-header">
      <h1>Todo List</h1>
      <span class="framework-badge">Vue.js</span>
    </div>

    <div class="todo-input-container">
      <input
        type="text"
        class="todo-input"
        placeholder="What needs to be done?"
        v-model="inputValue"
        @keypress="handleKeyPress"
        aria-label="New todo input"
      />
      <button 
        class="btn btn-primary" 
        @click="addTodo"
        aria-label="Add todo"
      >
        Add
      </button>
    </div>

    <div class="todo-filters">
      <button
        :class="['btn', 'filter-btn', { active: filter === 'all' }]"
        @click="filter = 'all'"
        aria-label="Show all todos"
      >
        All
      </button>
      <button
        :class="['btn', 'filter-btn', { active: filter === 'active' }]"
        @click="filter = 'active'"
        aria-label="Show active todos"
      >
        Active
      </button>
      <button
        :class="['btn', 'filter-btn', { active: filter === 'completed' }]"
        @click="filter = 'completed'"
        aria-label="Show completed todos"
      >
        Completed
      </button>
    </div>

    <div class="todo-stats">
      {{ remainingCount }} {{ remainingCount === 1 ? 'item' : 'items' }} remaining
    </div>

    <div v-if="filteredTodos.length === 0" class="empty-state">
      <div class="empty-state-icon">📝</div>
      <div class="empty-state-text">No todos to display</div>
    </div>
    <ul v-else class="todo-list">
      <li 
        v-for="todo in filteredTodos" 
        :key="todo.id" 
        :class="['todo-item', { completed: todo.completed }]"
      >
        <input
          type="checkbox"
          class="todo-checkbox"
          :checked="todo.completed"
          @change="toggleTodo(todo.id)"
          :aria-label="`Toggle ${todo.text}`"
        />
        <span class="todo-text">{{ todo.text }}</span>
        <button
          class="btn btn-delete"
          @click="deleteTodo(todo.id)"
          :aria-label="`Delete ${todo.text}`"
        >
          Delete
        </button>
      </li>
    </ul>

    <div class="todo-footer">
      Frontend Benchmark - Vue.js Implementation
    </div>
  </div>
</template>

<style>
@import './style.css';
</style>

// implementations/react/src/App.jsx
import { useState, useMemo } from 'react';
import './App.css';

// Generate initial todos
const generateInitialTodos = (count) => {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    text: `Todo item ${i + 1}`,
    completed: i % 3 === 0, // Every 3rd item is completed
  }));
};

function App() {
  const [todos, setTodos] = useState(() => generateInitialTodos(100));
  const [inputValue, setInputValue] = useState('');
  const [filter, setFilter] = useState('all'); // all, active, completed

  // Add new todo
  const addTodo = () => {
    if (inputValue.trim() === '') return;
    
    const newTodo = {
      id: Date.now(),
      text: inputValue,
      completed: false,
    };
    
    setTodos([newTodo, ...todos]);
    setInputValue('');
  };

  // Toggle todo completion
  const toggleTodo = (id) => {
    setTodos(todos.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  // Delete todo
  const deleteTodo = (id) => {
    setTodos(todos.filter(todo => todo.id !== id));
  };

  // Filter todos
  const filteredTodos = useMemo(() => {
    switch (filter) {
      case 'active':
        return todos.filter(todo => !todo.completed);
      case 'completed':
        return todos.filter(todo => todo.completed);
      default:
        return todos;
    }
  }, [todos, filter]);

  // Count remaining todos
  const remainingCount = useMemo(() => 
    todos.filter(todo => !todo.completed).length,
    [todos]
  );

  // Handle Enter key
  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      addTodo();
    }
  };

  return (
    <div className="todo-app">
      <div className="todo-header">
        <h1>Todo List</h1>
        <span className="framework-badge">React</span>
      </div>

      <div className="todo-input-container">
        <input
          type="text"
          className="todo-input"
          placeholder="What needs to be done?"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyPress={handleKeyPress}
          aria-label="New todo input"
        />
        <button 
          className="btn btn-primary" 
          onClick={addTodo}
          aria-label="Add todo"
        >
          Add
        </button>
      </div>

      <div className="todo-filters">
        <button
          className={`btn filter-btn ${filter === 'all' ? 'active' : ''}`}
          onClick={() => setFilter('all')}
          aria-label="Show all todos"
        >
          All
        </button>
        <button
          className={`btn filter-btn ${filter === 'active' ? 'active' : ''}`}
          onClick={() => setFilter('active')}
          aria-label="Show active todos"
        >
          Active
        </button>
        <button
          className={`btn filter-btn ${filter === 'completed' ? 'active' : ''}`}
          onClick={() => setFilter('completed')}
          aria-label="Show completed todos"
        >
          Completed
        </button>
      </div>

      <div className="todo-stats">
        {remainingCount} {remainingCount === 1 ? 'item' : 'items'} remaining
      </div>

      {filteredTodos.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">📝</div>
          <div className="empty-state-text">No todos to display</div>
        </div>
      ) : (
        <ul className="todo-list">
          {filteredTodos.map((todo) => (
            <li 
              key={todo.id} 
              className={`todo-item ${todo.completed ? 'completed' : ''}`}
            >
              <input
                type="checkbox"
                className="todo-checkbox"
                checked={todo.completed}
                onChange={() => toggleTodo(todo.id)}
                aria-label={`Toggle ${todo.text}`}
              />
              <span className="todo-text">{todo.text}</span>
              <button
                className="btn btn-delete"
                onClick={() => deleteTodo(todo.id)}
                aria-label={`Delete ${todo.text}`}
              >
                Delete
              </button>
            </li>
          ))}
        </ul>
      )}

      <div className="todo-footer">
        Frontend Benchmark - React Implementation
      </div>
    </div>
  );
}

export default App;
